# https://github.com/dunglas/frankenphp-wordpress/blob/main/docker-compose.yml

services:
  ap-site-wordpress:
    build: .
    restart: always
    ports:
      - "${LOCAL_HTTP_PORT:-11180}:80"
      - "${LOCAL_HTTPS_PORT:-11443}:443"
    environment:
      WORDPRESS_DB_HOST: staging-db.aspiredev.org
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    volumes:
      - ap-site-wordpress:/var/www/html
    networks:
      traefik: ~
      app-net: ~
      aspire-net:
        aliases:
          - 'staging.aspiredev.org'

  ap-site-db:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ap-site-db:/var/lib/mysql
    networks:
      app-net: ~
      aspire-net:
        aliases:
          - 'staging-db.aspiredev.org'

volumes:
  ap-site-wordpress:
  ap-site-db:

networks:
  app-net: ~
  aspire-net:
    external: true
  traefik:
    external: true
