services:
  ap-site-wordpress:
    build:
      context: .
      # target: dev
      target: prod
    restart: unless-stopped
    ports:
      - "${LOCAL_HTTP_PORT:-11180}:80"
      - "${LOCAL_HTTPS_PORT:-11443}:443"
    environment:
      WORDPRESS_DB_HOST: staging-db.aspiredev.org
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    # volumes:
    #   - .:/app
    networks:
      traefik: ~
      app-net: ~
      aspire-net:
        aliases:
          - 'staging.aspiredev.org'

  ap-site-db:
    image: mysql:8.4.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ap-site-db:/var/lib/mysql
    networks:
      app-net: ~
      aspire-net:
        aliases:
          - 'staging-db.aspiredev.org'

volumes:
  ap-site-wordpress:
  ap-site-db:

networks:
  app-net: ~
  aspire-net:
    external: true
  traefik:
    external: true
